apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "chart.fullname" . }}
spec:
  backendType: {{ .Values.externalSecrets.type }}
  region: {{ .Values.externalSecrets.region }}
  data:
        {{- range .Values.externalSecrets.body }}
          - key: {{ .key }}
            name: {{ .name }}
            property: {{ .property }}  
        {{- end }}
